language: generic
sudo: required
services:
 - docker

before_isntall:
 - docker build -t lalitdev90/react-test -f ./client/Dockerfile.dev ./client

 
script:
 - docker run -e CI=true lalitdev90/react-test npm test
  
after_success:
 - docker build -t lalitdev90/multi-client ./client
 - docker build -t lalitdev90/multi-nginx ./nginx
 - docker build -t lalitdev90/multi-server ./server
 - docker build -t lalitdev90/multi-worker ./worker
 # login to docker cli using "docker login"
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push push them to docker hub
 - docker push lalitdev90/multi-client
 - docker push lalitdev90/multi-nginx
 - docker push lalitdev90/multi-server
 - docker push lalitdev90/multi-worker
 # deploy on AWS  
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-539085793928'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY